### PR TITLE
Add metrics to the exemplar

### PR DESCRIPTION
**Pull request by dave-connors-3**
## Description & motivation

Our exemplar should be extended to include some simple metrics!

## Changes to existing models:

- updated the agg model that only relies on one model to use the metrics package

## Screenshots (DAG, query results):

image

## Checklist:

- [x] My pull request represents one logical piece of work.
- [x] My commits are related to the pull request and look clean.
- [x] My SQL follows the [dbt Labs style guide](https://github.com/dbt-labs/corp/blob/master/dbt_style_guide.md).
- [x] I have materialized my models appropriately.
- [x I have added appropriate tests and documentation to any new models or fields.
- [ ] I have noted if my changes break something in Looker and have a corresponding Looker PR to resolve the breaking change

### CODE REVIEW

**Comment by patkearns10** [comment]
Looks good to me! 
For some extra credit, you could add a model `agg_customer_orders__legacy.sql` with the original legacy sql, then setup an `analysis/compare_queries%` audit_helper model to show that they output the same!

**Review by patkearns10 — APPROVED** [review]
🌵

**Review by b-per — APPROVED** [review]
🥐

**Review by bennieregenold7 — APPROVED** [review]
🦊

**Review by cohms — COMMENTED** [review]
My only comment is more of a question of if we should name `agg_customer_orders` to `agg_customer_orders_all_time` instead, and really it's a double check on my understanding of how metrics work. In cases like this where we create a model off of a metric, the grain and dimensions are permanent, correct? Versus if an end user were to directly query the metric themselves in a BI tool, THEN they can specify the grain and dimensions themselves, right?

So only mentioning the model name change to be extra clear on the grain of the metric when we demo it and that in this particular model it can't change (if I have that right).

**Comment by dave-connors-3** [comment]
@cohms you're exactly right on all counts! my first stab here was actually to remove this model altogether, since it's a) redundant and b) inflexible compared to using the metric macro and the semantic layer together. 

I'm open to renaming for clarity too!

**Review by cohms — APPROVED** [review]
@dave-connors-3 definitely agree with you that the model isn't necessary. I definitely agree with keeping it and renaming it since it is a demo project and it could then be used to show clients that it's one option in how to use metrics (yes you _can_ build models off metrics, but it's redundant and inflexible, but at least it will be the same underlying metric if used in the semantic layer).

**Pull request merged**
