### PR TITLE
add python models, config, and sample queries

### PR DESCRIPTION
**Pull request by patkearns10**
## Description & motivation

Went through the [Python models documentation](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/python-models#specific-data-warehouses) and created similar .py models

Use cases covered:

using python builtin functions
using variables from project in config.yml (target.name) because you cannot declare or retrieve variables in the normal way
importing pypi packages (holiday)
define a function within the model (x*2)
add a snowpark anonymous udf function (add random int)

## Changes to existing models:

None

### command syntax is normal!
Screen Shot 2022-11-09 at 1 35 36 PM

#### `python_builtins__describe`
Screen Shot 2022-11-09 at 1 33 09 PM

#### `use_variables__customers_limit_10`
Screen Shot 2022-11-09 at 1 33 35 PM

#### `import_pypi_package__holiday`
Screen Shot 2022-11-09 at 1 33 53 PM

#### `define_function__payment_glitch`
Screen Shot 2022-11-09 at 1 34 20 PM

#### `add_udf_function__payment_glitch`
Screen Shot 2022-11-09 at 1 34 37 PM

### Lineage persists, and .py models can ref .py models!
Screen Shot 2022-11-09 at 1 42 28 PM

## Checklist:

- [x] My pull request represents one logical piece of work.
- [x] My commits are related to the pull request and look clean.
- [x] My SQL follows the [dbt Labs style guide](https://github.com/dbt-labs/corp/blob/master/dbt_style_guide.md).
- [x] I have materialized my models appropriately.
- [x] I have added appropriate tests and documentation to any new models or fields.
- [x] I have noted if my changes break something in Looker and have a corresponding Looker PR to resolve the breaking change

### CODE REVIEW

**Comment by b-per** [comment]
I like showcasing Python, but instead of showing all the ways Python can be used, wouldn't it be better to show a real use case with models not named after the use case we want to demonstrate, but named after the output data (like normal models)?

My impression is that the RO exemplar shouldn't try to cover all use cases but demonstrate how a small but well-defined project should look like. (defining what we want the RO exemplar project to be might be a bigger conversation in itself)

**Review by wasilaq — COMMENTED** [review]
I agree with Benoit. There's some awesome stuff in here, but I'm not sure if this fits into the RO exemplar project. It feels more like a review of Python models as opposed to how a Python model would be integrated into a real project.

It would definitely be cool to save these somewhere though, even if it's a different repo.

**Comment by jeremyholtzman** [comment]
I go back and fort on it. I agree with Benoit and Wasila in terms of wanting the repo to show what an ideal project would look like. However, I often find myself wanting to quickly demonstrate more advanced topics like some of these python models, and having it available in a central location is really nice. I mentioned this in slack, but it might be great to have a larger conversation with @MichelleBaird-DBT about this repo and where everything should live.

**Comment by bennieregenold7** [comment]
@patkearns10 - I was playing around in this project to learn how to use Python models, and might have a realistic use case. I didn't put it in the right place because I was just doing it quick, but [this model](https://github.com/dbt-labs/rapid-onboarding-exemplar/blob/br_python_example/models/marts/marketing/phone_number_cleaning.py) takes the phone numbers and puts their respective country codes in front using a package. Maybe we could incorporate this?

It also uses [this seed file](https://github.com/dbt-labs/rapid-onboarding-exemplar/blob/br_python_example/seeds/country_codes.csv) to get the country codes, and requires one additional join in [dim_customers](https://github.com/dbt-labs/rapid-onboarding-exemplar/blob/br_python_example/models/marts/marketing/dim_customers.sql#L45).

**Comment by patkearns10** [comment]
@b-per - I agree, but the project is so small (only tpch) which is altogether not a good depiction of what a company's project would look like, so I'd rather it be more useful in explaining, with lots of demo opportunities baked in for us to showcase features. 

@bennieregenold7 That example seems like a good one to add in! 

I'll let @MichelleBaird-DBT make a decision on the future state, and happy to make any changes to fit the ideal.

**Pull request merged**
