### PR TITLE
Removed dbt_utils

### PR DESCRIPTION
**Pull request by christineberger**
## Checklist:

- [ ] My pull request represents one logical piece of work.
- [ ] My commits are related to the pull request and look clean.
- [ ] My SQL follows the [dbt Labs style guide](https://github.com/dbt-labs/corp/blob/master/dbt_style_guide.md).
- [ ] I have materialized my models appropriately.
- [ ] I have added appropriate tests and documentation to any new models or fields.
- [ ] I have noted if my changes break something in Looker and have a corresponding Looker PR to resolve the breaking change

### CODE REVIEW

**Comment by epapineau** [comment]
We use dbt_utils in [stg_tpch_line_items](https://github.com/dbt-labs/rapid-onboarding-exemplar/blob/master/models/staging/tpch/stg_tpch_line_items.sql#L12)

**Comment by christineberger** [comment]
Sorry Elize! I thought I deleted this - I was exemplifying for Ally's RO 😅

**Comment by epapineau** [comment]
No problem - thought I would reply just in case :) Quick question - shouldn't the CI job have failed when you removed this dependency?

**Comment by christineberger** [comment]
The CI job is set up to defer. Not saying this is the reason it didn't fail, but it's likely because it only runs changes that there were no changed models and it went through without a hitch. Something we should surface if that's really the case, but I think we'll need to test it out again to make sure it isn't something else!

**Pull request closed without merging**
